# Model Question paper solution

### PYTHON, NUMPY, PANDAS, DATA VISUALIZATION

In [6]:
# 5) Define a Python function to find the minimum and maximum values from a list. (5Marks)

def max_min(a_list):
    maximum = max(a_list)
    minimum = min(a_list)
    print(f"Maximum =  {maximum} Minimum = {minimum}")
max_min([10,20,30,60,-5])

Maximum =  60 Minimum = -5


In [2]:
# 6) Create a 3x3 NumPy array of ones and find out the total memory used for the array, (5Marks)

import numpy as np 
array = np.array([[1,1,1],
                  [1,1,1],
                  [1,1,1]])
print("size of an array :",array.shape)
print("Memory size of numpy array :", array.nbytes)


size of an array : (3, 3)
Memory size of numpy array : 36


In [4]:
# 7) Load the ODI_data.csv file using Pandas and print first 10 rows of the data. Find out the shape of the data.
import pandas as pd 
import matplotlib.pyplot as plt

# Importing the data set
data = pd.read_csv('ODI_data.csv')

# Printing 10 Rows of data
data.head(50)

Unnamed: 0                        Player       Span  Mat Inns  NO   Runs  \
0            0          SR Tendulkar (INDIA)  1989-2012  463  452  41  18426   
1            1   KC Sangakkara (Asia/ICC/SL)  2000-2015  404  380  41  14234   
2            2          RT Ponting (AUS/ICC)  1995-2012  375  365  39  13704   
3            3       ST Jayasuriya (Asia/SL)  1989-2011  445  433  18  13430   
4            4    DPMD Jayawardene (Asia/SL)  1998-2015  448  418  39  12650   
5            5     Inzamam-ul-Haq (Asia/PAK)  1991-2007  378  350  53  11739   
6            6               V Kohli (INDIA)  2008-2019  242  233  39  11609   
7            7        JH Kallis (Afr/ICC/SA)  1996-2014  328  314  53  11579   
8            8       SC Ganguly (Asia/INDIA)  1992-2007  311  300  23  11363   
9            9     R Dravid (Asia/ICC/INDIA)  1996-2011  344  318  40  10889   
10          10         MS Dhoni (Asia/INDIA)  2004-2019  350  297  84  10773   
11          11             CH Gayle (ICC/WI)  1999-2019  301  294  17  10480   
12          12              BC Lara (ICC/WI)  1990-2007  299  289  32  10405   
13          13               TM Dilshan (SL)  1999-2016  330  303  41  10290   
14          14    Mohammad Yousuf (Asia/PAK)  1998-2010  288  273  40   9720   
15          15        AC Gilchrist (AUS/ICC)  1996-2008  287  279  11   9619   
16          16       AB de Villiers (Afr/SA)  2005-2018  228  218  39   9577   
17          17          M Azharuddin (INDIA)  1985-2000  334  308  54   9378   
18          18              PA de Silva (SL)  1984-2003  308  296  30   9284   
19          19             RG Sharma (INDIA)  2007-2019  221  214  32   8944   
20          20             Saeed Anwar (PAK)  1989-2003  247  244  19   8824   
21          21            S Chanderpaul (WI)  1994-2011  268  251  40   8778   
22          22     Yuvraj Singh (Asia/INDIA)  2000-2017  304  278  40   8701   
23          23                DL Haynes (WI)  1978-1994  238  237  28   8648   
24          24              MS Atapattu (SL)  1990-2007  268  259  32   8529   
25          25                ME Waugh (AUS)  1988-2002  244  236  20   8500   
26          26              LRPL Taylor (NZ)  2006-2019  228  212  37   8376   
27          27     V Sehwag (Asia/ICC/INDIA)  1999-2013  251  245   9   8273   
28          28                  HM Amla (SA)  2008-2019  181  178  14   8113   
29          29                 HH Gibbs (SA)  1996-2010  248  240  16   8094   
30          30  Shahid Afridi (Asia/ICC/PAK)  1996-2015  398  369  27   8064   
31          31           SP Fleming (ICC/NZ)  1994-2007  280  269  21   8037   
32          32               MJ Clarke (AUS)  2003-2015  245  223  44   7981   
33          33                SR Waugh (AUS)  1986-2002  325  288  58   7569   
34          34            Shoaib Malik (PAK)  1999-2019  287  258  40   7534   
35          35              A Ranatunga (SL)  1982-1999  269  255  47   7456   
36          36           Javed Miandad (PAK)  1975-1996  233  218  41   7381   
37          37          EJG Morgan (ENG/IRE)  2006-2019  233  217  32   7348   
38          38             Younis Khan (PAK)  2000-2015  265  255  23   7249   
39          39            Saleem Malik (PAK)  1982-1999  283  256  38   7170   
40          40                 NJ Astle (NZ)  1995-2007  223  217  14   7090   
41          41             GC Smith (Afr/SA)  2002-2013  197  194  10   6989   
42          42         WU Tharanga (Asia/SL)  2005-2019  235  223  17   6951   
43          43                MG Bevan (AUS)  1994-2004  232  196  67   6912   
44          44           Tamim Iqbal (BDESH)  2007-2019  204  202   8   6892   
45          45                G Kirsten (SA)  1993-2003  185  185  19   6798   
46          46                A Flower (ZIM)  1992-2003  213  208  16   6786   
47          47             IVA Richards (WI)  1975-1991  187  167  24   6721   
48          48               MJ Guptill (NZ)  2009-2019  179  176  19   6626   
49  

In [62]:
# Find out the shape of the data
data.shape

(2500, 15)

### Data Preprocessing and ML Algorithms

In [8]:
# 11) Implement the following preprocessing steps ( Data_Train_Cars.xlsx)

# Importing the dataset
import pandas as pd
dataset = pd.read_excel('Data_Train_Cars.xlsx')
dataset.shape

(6019, 13)

In [9]:
# a) Printing First and last five rows of data
dataset.head(5)

Name    Location  Year  Kilometers_Driven  \
0            Maruti Wagon R LXI CNG      Mumbai  2010              72000   
1  Hyundai Creta 1.6 CRDi SX Option        Pune  2015              41000   
2                      Honda Jazz V     Chennai  2011              46000   
3                 Maruti Ertiga VDI     Chennai  2012              87000   
4   Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013              40670   

  Fuel_Type Transmission Owner_Type     Mileage   Engine      Power  Seats  \
0       CNG       Manual      First  26.6 km/kg   998 CC  58.16 bhp    5.0   
1    Diesel       Manual      First  19.67 kmpl  1582 CC  126.2 bhp    5.0   
2    Petrol       Manual      First   18.2 kmpl  1199 CC   88.7 bhp    5.0   
3    Diesel       Manual      First  20.77 kmpl  1248 CC  88.76 bhp    7.0   
4    Diesel    Automatic     Second   15.2 kmpl  1968 CC  140.8 bhp    5.0   

   New_Price  Price  
0        NaN   1.75  
1        NaN  12.50  
2  8.61 Lakh   4.50  
3        NaN   6.00  
4        NaN  17.74

In [10]:
dataset.tail(5)

Name   Location  Year  Kilometers_Driven Fuel_Type  \
6014          Maruti Swift VDI      Delhi  2014              27365    Diesel   
6015  Hyundai Xcent 1.1 CRDi S     Jaipur  2015             100000    Diesel   
6016     Mahindra Xylo D4 BSIV     Jaipur  2012              55000    Diesel   
6017        Maruti Wagon R VXI    Kolkata  2013              46000    Petrol   
6018     Chevrolet Beat Diesel  Hyderabad  2011              47000    Diesel   

     Transmission Owner_Type     Mileage   Engine     Power  Seats  New_Price  \
6014       Manual      First   28.4 kmpl  1248 CC    74 bhp    5.0  7.88 Lakh   
6015       Manual      First   24.4 kmpl  1120 CC    71 bhp    5.0        NaN   
6016       Manual     Second   14.0 kmpl  2498 CC   112 bhp    8.0        NaN   
6017       Manual      First   18.9 kmpl   998 CC  67.1 bhp    5.0        NaN   
6018       Manual      First  25.44 kmpl   936 CC  57.6 bhp    5.0        NaN   

      Price  
6014   4.75  
6015   4.00  
6016   2.90  
6017   2.65  
6018   2.50

In [11]:
# b) Perform complete profiling of the data by Pandas profiling. (5 Marks)

!pip install pandas-profiling

You should consider upgrading via the 'C:\Users\GOVIND\anaconda3\python.exe -m pip install --upgrade pip' command.


In [12]:
from pandas_profiling import ProfileReport
prof = ProfileReport(dataset)
prof.to_file(output_file='output.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [13]:
# c) Find out if any missing values and impute it with median 
dataset.isnull().sum()

Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  42
New_Price            5195
Price                   0
dtype: int64

In [15]:
dataset['Mileage']=dataset['Mileage'].apply(lambda x : str(x).split(" ")[0]).astype(np.float64)
dataset['Engine']=dataset['Engine'].apply(lambda x : str(x).split(" ")[0]).astype(np.float64)
dataset['Power']=dataset['Power'].replace('null bhp','0 bhp').apply(lambda x : str(x).split(" ")[0]).astype(np.float64)
dataset['New_Price']=dataset['New_Price'].replace(np.nan,'0 Lakh').apply(lambda x : str(x).split(" ")[0]).astype(np.float64).replace(0.00,np.nan)

In [16]:
dataset['Engine']=dataset.transform(lambda x: x.fillna(x.median()))['Engine']
dataset['Power']=dataset.transform(lambda x: x.fillna(x.median()))['Power']
dataset['Seats']=dataset.transform(lambda x: x.fillna(x.median()))['Seats']
dataset['Mileage']=dataset.transform(lambda x: x.fillna(x.median()))['Mileage']
dataset['New_Price']=dataset.transform(lambda x: x.fillna(x.median()))['New_Price']

C:\Users\GOVIND\AppData\Local\Temp/ipykernel_25700/2207558933.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dataset['Engine']=dataset.transform(lambda x: x.fillna(x.median()))['Engine']
C:\Users\GOVIND\AppData\Local\Temp/ipykernel_25700/2207558933.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dataset['Power']=dataset.transform(lambda x: x.fillna(x.median()))['Power']
C:\Users\GOVIND\AppData\Local\Temp/ipykernel_25700/2207558933.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reducti

In [17]:
dataset.isnull().sum()

Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
New_Price            0
Price                0
dtype: int64

In [19]:
dataset.head(10)

Name    Location  Year  Kilometers_Driven  \
0               Maruti Wagon R LXI CNG      Mumbai  2010              72000   
1     Hyundai Creta 1.6 CRDi SX Option        Pune  2015              41000   
2                         Honda Jazz V     Chennai  2011              46000   
3                    Maruti Ertiga VDI     Chennai  2012              87000   
4      Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013              40670   
5      Hyundai EON LPG Era Plus Option   Hyderabad  2012              75000   
6               Nissan Micra Diesel XV      Jaipur  2013              86999   
7    Toyota Innova Crysta 2.8 GX AT 8S      Mumbai  2016              36000   
8  Volkswagen Vento Diesel Comfortline        Pune  2013              64430   
9       Tata Indica Vista Quadrajet LS     Chennai  2012              65932   

  Fuel_Type Transmission Owner_Type  Mileage  Engine   Power  Seats  \
0       CNG       Manual      First    26.60   998.0   58.16    5.0   
1    Diesel       Manual      First    19.67  1582.0  126.20    5.0   
2    Petrol       Manual      First    18.20  1199.0   88.70    5.0   
3    Diesel       Manual      First    20.77  1248.0   88.76    7.0   
4    Diesel    Automatic     Second    15.20  1968.0  140.80    5.0   
5       LPG       Manual      First    21.10   814.0   55.20    5.0   
6    Diesel       Manual      First    23.08  1461.0   63.10    5.0   
7    Diesel    Automatic      First    11.36  2755.0  171.50    8.0   
8    Diesel       Manual      First    20.54  1598.0  103.60    5.0   
9    Diesel       Manual     Second    22.30  1248.0   74.00    5.0   

   New_Price  Price  
0     11.415   1.75  
1     11.415  12.50  
2      8.610   4.50  
3     11.415   6.00  
4     11.415  17.74  
5     11.415   2.35  
6     11.415   3.50  
7     21.000  17.50  
8     11.415   5.20  
9     11.415   1.95

### BEST PRACTICES AND OPTIMIZATION IN ML

In [20]:
# 12) Consider the Customer_Purchases.csv dataset and perform the following operations.
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [21]:
# Importing the dataset 
dataset = pd.read_csv('Customer_Purchases.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [22]:
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [23]:
dataset.shape

(400, 3)

In [24]:
# Spliting the dataset into the training dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [25]:
# Feature Scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [26]:
# Training the Decision Tree Classification model on the Training set
# a) Criterion as Entropy
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0, max_depth = 3)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)

In [27]:
# Predicting a new result
print(classifier.predict(sc.transform([[19,19000]])))

[0]


In [28]:
# Predicting the test set result
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]


In [29]:
# Making Confusion matrix (Accuracy)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[64  4]
 [ 2 30]]


0.94

In [30]:
# b) Criterion as gini
classifier = DecisionTreeClassifier(criterion = 'gini', random_state = 0,  max_depth = 3)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=0)

In [31]:
# Predicting a new result
print(classifier.predict(sc.transform([[35,20000]])))

[0]


In [32]:
# Predicting the test set result
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]


In [33]:
# Making Confusion matrix (Accuracy)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[64  4]
 [ 2 30]]


0.94

In [34]:
# Conclusion
# a) Accuracy when Criterion is Entropy = 0.94
# b) Accuracy when Criterion is gini    = 0.94